### ISSUE TITLE
Review 1: Error 

### ISSUE THREAD

**Issue by priyandari** [elvabunga/Kelompok-05#1]
===================INFORMASI JABATAN, GAJI POKOK, DAN TUNJANGAN===================                                                                                                  No.      Jabatan         Gaji Pokok      Tunjangan                                        1        Direktur        7000000         3000000                                          2        Manager         5000000         2000000                                          3        Supervisor      3000000         1500000                                          4        Staff           2000000         1000000                                          5        Janitor         1000000         500000                                           Nama Karyawan : Adi                                                                       Nomor Induk Pegawai : 023                                                                 Nomor Jabatan : 2                                                                         Banyak cuti : 0                                                                           Banyaknya jam lembur : 8                                                                  Banyaknya masuk di tanggal merah atau hari Minggu : 0                                     Banyaknya jam keterlambatan : 0.5                                                         Traceback (most recent call last):                                                          File "HitungGaji.py", line 208, in <module>                                                 proses()                                                                                File "HitungGaji.py", line 65, in proses                                                    t = int(input('Banyaknya jam keterlambatan : '))                                      ValueError: invalid literal for int() with base 10: '0.5'

**Comment by priyandari** [comment]
![Capture2](https://user-images.githubusercontent.com/4914090/83823809-15277480-a6ff-11ea-8675-b427fa94938e.PNG)

**Comment by priyandari** [comment]
Itu belum diselesaikan
